# Generated by Django 2.2 on 2019-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db2user',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
